### ISSUE TITLE
wrong number of captured cams

### ISSUE THREAD

**Issue by marabu88** [falsovsky/chaturbate#10]
After some time i see this (model names replaced, but this is part real info):
```
...
2017-02-14 09:07:42 INFO Ignore model: model5
2017-02-14 09:07:42 INFO Ignore model: model6
2017-02-14 09:07:42 INFO Recording: model1 - Duration: 2:13:32 - Size: 755.77 MB
2017-02-14 09:07:42 INFO Capturing: 3, Processing: 0
```
How you see - script record only one model, but in report - 3! You think this is problem have only my version because i remove check for private cams?

In process explorer i see 2 old not closed streams :( and files for this streams have 0 size. Even if that private flows, why rtmpdump still trying to capture them?

You know about away status? Maybe you know how close capture stream if this is don't update more, but rtmpdump continue capture it?

Right now i try return your check for private streams :)

**Comment by marabu88** [comment]
I'm testing an option with your check. I think that the problems will be no more, but I do not like that for some time a recorded stream is deleted during the scan. That is why I deleted it from my version.

It seems to me forced termination of recording, if the file is within a certain time does not increase - it is the preferred option. What do you think about it?

**Comment by marabu88** [comment]
Bad news for BOTH versions (with private check and without)

rtmpdump sometimes creates a zero-length file and does not end on their own :( This leads to various problems in the version with and without test

In my version (without check): some streams may hang and perhaps when the thread with the same model runs the script does not record it again, because it considers that the record goes. In addition, given the wrong information about the number of actual recorded flows.

In your: still worse - because your script is not multi-threaded, it just hangs waiting for the completion of work rtmpdump
```
2017-02-15 02:47:21 INFO Model model is chaturbating
2017-02-15 02:47:22 INFO .. model -> GET INFO
2017-02-15 02:47:22 INFO Model model -> START CHECK PRIVATE
```
This variant script waits for a response for several hours. Is real data. My version continues to work and record new models.

I see the only solution - to remove your version check and add the forced closure rtmpdump if the file is a zero-length for a certain time.

you can do this or do I have to try independently?

**Comment by chopraaa** [comment]
Please post problems related to this repo, and not your own fork.

Also, thanks for the migraine. English isn't my first language either but my head hasn't hurt this bad in ages.

**Comment by falsovsky** [comment]
Hello, i'm not interested in your changes because they dont make any sense.

Also, the problems you're having are because you deleted code that you shoulnt have.

**Comment by marabu88** [comment]
should be, my english is too bad and I could not explain to you what I mean with sufficient accuracy. If your program has more users, you would have realized that there is a problem. Try to run your script with a lot of models for 1-2 days. You will see that there are problems.

I return your validation code (without changing its !!!!) and the script just frozen in an endless waiting rtmpdump completion. Do not you think that this is quite a serious problem ???

**Comment by falsovsky** [comment]
Mine works correctly for me.
