### ISSUE TITLE
Capture by keyword or other parameters

### ISSUE THREAD

**Issue by marabu88** [falsovsky/chaturbate#11]
The program for the MFC I added a record by keyword. But there it was easy, as was originally used list, where they were shown the chat topic, country, age, model, etc.

What do you think about in order to add the ability to record some cams in the description of keywords, age, sex models?

Of course for this you need to add the ability to scan a complete list of models that are online. Previously, there was a page which displays all models at once. Now this page is not :(

**Comment by falsovsky** [comment]
I cant understand what you write. 
I made this script for me, and for that I need it works, if you need any changes, make on yours.
