### ISSUE TITLE
how about add igonre list ?

### ISSUE THREAD

**Issue by tempstack** [falsovsky/chaturbate#12]

**Comment by falsovsky** [comment]
Just unfollow the model, and it wont record it anymore.

**Comment by tempstack** [comment]
i wont temprorary add to ignored list

ok. DIY !

**Comment by falsovsky** [comment]
Yes, I don't really like that idea, so if you want it, just fork the project, and do it yourself.

**Comment by ticklemynausea** [comment]
ｔ　ｏ　ｐ　　　ｋ　ｅ　ｋ
