### ISSUE TITLE
Stuttering frames.

### ISSUE THREAD

**Issue by chopraaa** [falsovsky/chaturbate#15]
I'm recording one stream at a time and there's a huge amount of stutter. Tested with 3 models and all the clips have it.

Pretty sure it's not my network...

![Speedtest.](http://www.speedtest.net/result/6165398828.png)

[Here's](https://giphy.com/gifs/13FYGQU9bSwne0/html5) one of the clips. (nsfw)

**Comment by falsovsky** [comment]
Well, it works for me :)

Probably is the hard drive speed
