### ISSUE TITLE
error in osx

### ISSUE THREAD

**Issue by grissom02** [falsovsky/chaturbate#16]
Hello, I'm receiving this error after run python chaturbate.py

`Traceback (most recent call last):
  File "chaturbate.py", line 629, in <module>
    c = Chaturbate()
  File "chaturbate.py", line 63, in __init__
    self.detect_rtmpdump()
  File "chaturbate.py", line 147, in detect_rtmpdump
    output = subprocess.check_output(arguments, stderr=subprocess.STDOUT)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 567, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory`

**Comment by falsovsky** [comment]
Well you dont seem to have rtmpdump installed.

**Comment by grissom02** [comment]
Thank you.
I'm trying to install it via brew, but after install and run chaturbate.py, I received this:
rtmpdump-ksv not detected

Can you give some advice to install it?

thanks again!

**Comment by falsovsky** [comment]
I dont use OSX.

You cant use the rtmpdump from brew... You need to use the one I specify in the README.

**Comment by grissom02** [comment]
Ok, thanks for the help. I was able to install the right one.
The capturebate runs, but tells me:
WARNING But the show is private 

I did check online and the show is not private... openssl is installed too...

**Comment by falsovsky** [comment]
Well, im not really able to help with that...

Works for me...

**Comment by grissom02** [comment]
Ok, thanks any way. It must be something to do with osx. I'll test it in a virtualmachine.
Can you tell me what distro you are using?

**Comment by falsovsky** [comment]
It works for me on:
* Gentoo amd64
* OpenBBSD amd64
* ArchLinux aarm64

But it will work anywhere, youre just doing something wrong :-P

You probably have two versions of rtmpdump, and its finding the invalid one.

**Comment by grissom02** [comment]
Thanks, I was able to get it working on osx.
Follow this: http://stream-recorder.com/forum/use-rtmpdump-mac-os-x-t8122.html 
and now it's recording. I think it's working fine! Great job making this code!
Greetings from Brasil!

**Comment by grissom02** [comment]
I was able to install rtmpdump ksv on a ubuntu VM, when I type rtmpdump it
says ok,
but when I run python chaturbate.py it says: rtmpdump-ksv not detected!

can you help me fix that?

**Comment by falsovsky** [comment]
You probably have two versions of rtmpdump installed, one on /usr/bin from Ubuntu... and one on /usr/local/bin...
