### ISSUE TITLE
WARNING But the show is private

### ISSUE THREAD

**Issue by andyrav** [falsovsky/chaturbate#17]
Hi
Why do i keep getting WARNING But the show is private. i can view it on the browser ok?
many thanks

**Comment by vuteneseg** [comment]
Same problem here, This is my first time using this script so not sure if is my error or chaturbate has made server changes in the last few days. Falsovsky can you still capture video?

**Comment by falsovsky** [comment]
You have two versions of rtmpdump installed probably.

**Comment by Aussi25** [comment]
Sorry to jump on this but same issue here. Clean install ubuntu 16.04 amd64 with nothing installed but the requirements listed in the readme and rtmpdump-ksv compiled from https://github.com/BurntSushi/rtmpdump-ksv with libssl-dev

running a find / -iname "*rtmp*" only reveals 1 location for rtmpdump so no duplicates.
