### ISSUE TITLE
Warning the show is private

### ISSUE THREAD

**Issue by Aussi25** [falsovsky/chaturbate#20]
I saw the closed issue on this but i'm also experiencing this problem (and for sure don't have multiple rtmpdump installs).

Clean install ubuntu 16.04 amd64, Python 2.7.12 & Python 3.5.2 with nothing installed but the requirements listed in the readme and rtmpdump-ksv compiled from https://github.com/BurntSushi/rtmpdump-ksv with libssl-dev

running a find / -iname "*rtmp*" only reveals 1 location for rtmpdump so no duplicates.

Can I ask what distro/python version the author is running so I can attempt to replicate there or just avoid this bug that way?

**Comment by bust3r** [comment]
Same here on Lubuntu 17.04
Getting ERROR: Closing connection: NetStream.Play.Failed

see attached file
[debug.txt](https://github.com/falsovsky/chaturbate/files/1320743/debug.txt)

**Comment by falsovsky** [comment]
Well it works correctly. Because I run it on Ubuntu / Arch / Gentoo and OpenBSD.

You probably have an invalid librtmp and its using that one.

**Comment by bust3r** [comment]
Thank you for this hint.
Installed librtmp-dev from ubuntu repo and python-librtmp with pip3 
Now it's working

**Comment by falsovsky** [comment]
Nice, lets hope that the rest of the people see your comment.

**Comment by tawm** [comment]
I had this issue, your pointer to a "invalid librtmp" helped me to fix it. I just uninstalled the librtmp that was already on the system (duh!) and "make install"ed the one from rtmpdump-ksv in its place. Worked like a charm after, thank you for your work!
