### ISSUE TITLE
all shows private

### ISSUE THREAD

**Issue by schattenkrieger** [falsovsky/chaturbate#3]
hello,

just installed your scripts on raspian, the script is starting witout any problems but all shows a being reported as being private and nothing is recorded.

**Comment by falsovsky** [comment]
Did you also installed rtmpdump-ksv  https://github.com/BurntSushi/rtmpdump-ksv as is specified on the README?

**Comment by schattenkrieger** [comment]
As far as i can tell yes. 
I cloned the repository, and issues make SYS=posix, followed by make install. 
Both commands resulted in a lot of output and i have no idea if it was succesfull or not. When i issue rtmpdump i get some Info about the Version (v2.4) but i have no idea if it is actually working or not.

**Comment by falsovsky** [comment]
I did a commit right now, please see if it fixes it!

**Comment by schattenkrieger** [comment]
Thanks for the replay, sadly your changes did not correct anything for me. Any tips how i can verify that rtmpdump-ksv is installed correctly and actually working?

**Comment by falsovsky** [comment]
Try to following.

Delete this line from the script:

https://github.com/falsovsky/chaturbate/blob/master/chaturbate.py#L168

That will make rtmpdump show the ouput, and you'll be able to see why it is failing.

**Comment by schattenkrieger** [comment]
Here the error output after the change:

2016-08-24 06:25:49 INFO Model emma_and_adam is chaturbating
RTMPDump v2.4
(c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
Connecting ...
INFO: Connected...
ERROR: Closing connection: NetStream.Play.Failed
2016-08-24 06:25:52 WARNING But the show is private

**Comment by falsovsky** [comment]
Please do the following and give me the output:

`ls -sl /usr/bin/rtmpdump /usr/local/bin/rtmpdump`

That error ocurrs when not using the correct rtmpdump, you probably have two versions installed?
To test I deleted my rtmpdump, and installed the normal one, and I got the same error as you.

```
falso@fishy ~/chaturbate $ python chaturbate.py
2016-08-24 08:21:03 WARNING Not logged in
2016-08-24 08:21:03 INFO Logging in...
2016-08-24 08:21:06 INFO Model hotblondyx is chaturbating
RTMPDump v2.4
(c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
Connecting ...
INFO: Connected...
ERROR: Closing connection: NetStream.Play.Failed
2016-08-24 08:21:07 WARNING But the show is private
```

I now added a method to verify the rtmpdump version upon startup 47230cd7d0935f5deffa4b6895e52b50ab19e88a

**Comment by falsovsky** [comment]
Hi,

I just tried this in a Debian VM and it seems that rtmpdump is building with some problem on Debian, because the same that happens to you happens me there.

**Comment by schattenkrieger** [comment]
I had a rtmpdump in both folders. After apt-get remove rtmpdump only the one in /usr/local remains. 

Still not working, but as you write this seems to be a problem with debian. 

I still have a different raspberrypi gathering Dust. So i would be easy to set up a new System. 
Any idea what could work?

**Comment by falsovsky** [comment]
I found the problem. Its a problem with librtmp on debian and maybe ubuntu. In those distributions a lot of packages depend on librtmp, and you cant remove it.

And rtmpdump-ksv requires a different librtmp that is shipped with it.

I found a "dirty" fix ;-)

Go to your rtmpdump sources. 

```
falso@debian:~/src/rtmpdump-ksv$ ldd rtmpdump
        linux-vdso.so.1 (0x00007fff833f7000)
        librtmp.so.1 => /usr/lib/x86_64-linux-gnu/librtmp.so.1 (0x00007f887257e000)
        libssl.so.1.0.0 => /usr/lib/x86_64-linux-gnu/libssl.so.1.0.0 (0x00007f887231d000)
        libcrypto.so.1.0.0 => /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.0 (0x00007f8871f21000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f8871d06000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f8871a05000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f887165a000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f8871456000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f887279c000)
falso@debian:~/src/rtmpdump-ksv$
```
Look at the line that says librtmp.so.1, in yours the path to it will be different. Then do the following

```
falso@debian:~/src/rtmpdump-ksv$ cd librtmp/
falso@debian:~/src/rtmpdump-ksv/librtmp$ sudo cp librtmp.so.1 /usr/lib/x86_64-linux-gnu/librtmp.so.1
```
Change the path there according to ldd output.

After this rtmpdump-ksv should work :-)

At least in here it worked.

**Comment by schattenkrieger** [comment]
thanks,

seems to be working. will report back in a few hours and see what has been captured
