### ISSUE TITLE
Getting error while running python

### ISSUE THREAD

**Issue by t72a72** [falsovsky/chaturbate#5]
I got a fresh ubuntu install, and ran into some problems. I ran git clone, went into the folder and used pip install on the requirements (with no errors) and when I run python chaturbate.py I just get an [error](http://i.imgur.com/1TFODyC.png), what I don't get it the configuration part tho because what do you mean with config.ini.dist to config.ini? I don't have a folder called config.ini or do you just mean you have to change the name config.ini.dist to config.ini?

**Comment by falsovsky** [comment]
You have a file called config.ini.dist, make a copy of it and call it config.ini.

Then edit that file, and put your username and password.
