### ISSUE TITLE
Resource usage?

### ISSUE THREAD

**Issue by chopraaa** [falsovsky/chaturbate#6]
Anyone here have an estimate of the resources (CPU, RAM) this uses?

I have a server for educational purposes (lol) but it's limited on resources. _Very_ limited.

**Comment by falsovsky** [comment]
On a raspberry pi or something like that I think it will work OK, at least if writting to something fast.

If youre saying a router or something like that, i dont really know :-)

**Comment by chopraaa** [comment]
What exactly is ffmpeg being used for?

**Comment by falsovsky** [comment]
Its not really needed, you dont need to use it.
Its to transcode the speex audio to aac.

**Comment by chopraaa** [comment]
Not sure if it's working. o.0 "But the show is private."
I'll let it run for a bit, see where it goes. 

Also, it fails to detect some models, I suppose. I had just 1 at the start, ran the script to test it, got errors on lines 633, 513, 296. I have 3 right now but it's only checking one of them too.

Tired as fuck. Probably doing something wrong.

**Comment by falsovsky** [comment]
Just to report to you that I believe I've fixed the ffmpeg processing part. I just tried it for a few hours now, but I believe that I have fixed it now :-)
