### ISSUE TITLE
My fork

### ISSUE THREAD

**Issue by marabu88** [falsovsky/chaturbate#9]
I try do some changes in your project 
https://github.com/marabu88/chaturbate/tree/marabu88-patch-1
Don't ideal - but this is work
I don't know best way for share it with you. I just edit it in EditPlus and upload as fork
If you like it - can add my changes in your programm. If not - i can delete it
And sorry - my english not very good and i don't know how use GitHub :)

**Comment by falsovsky** [comment]
I cant even understand where are the changes. You changed every line.

**Comment by falsovsky** [comment]
I dont understand what do you want to do there? Instead of FOLLOWING on the site, use a local file with the models you want to record?

**Comment by falsovsky** [comment]
You disabled the part to check if the show is private.

**Comment by falsovsky** [comment]
I think you didnt understand how the script works. You need to have an account on the site, and then for each model you want to record, you just need to follow it.

**Comment by marabu88** [comment]
I'm sorry, but that you do not understand what exactly I changed :)

1) I changed not every line, I just replaced the space characters on the tabs, and remove some blank (I like a more compact code). I was not going to share it with someone, he did for himself.

2) wishlist.txt was added the same as another project, which I found earlier and used it (it worked only on Linux and I had to adapt it for Windows)

What is this for?!

For example, I have a lot of models in Section FOLLOWING. After starting your program on my disk is full 2Tb + less than a month. But I do not want to delete all the models, I do not want to write, as some models that did not interest me at the moment, can change the show better. This happens. And I can just forget about them. Why not ignorelist? I first had the idea, but much less wishlist :)

You can implement both options, if you want. But I think that you will not do anything like that. Maybe you enough that is. I - no.

3)  Yes, I deleted the verification of private video. I did not like the way you used to do. My version works just as well. If I am not mistaken, the private video are eliminated on the boot stage FOLLOWING section.

I also want to express my gratitude for this script. It's not perfect, but it is a good basis for further work. Hopefully we will be useful to each other. If you want, we can establish a connection via skype or something like that.

**Comment by falsovsky** [comment]
The private videos still appear on the Following page.

**Comment by falsovsky** [comment]
So let me see if I understood:

You follow 50 cams, but you just want to record from three of them.
Then you add to wishlist.txt

Model1
Model2
Model3

And the script just records those three models instead of the 50, right ?

**Comment by marabu88** [comment]
Yes! All right :) 

And i have some more ideas - like comments for models in list. Just add something after model name:
```
model1 - very hot
-model_2 - no some special :) 
mo_de_l3 - added 2016/10/01
```
If "-" before model name - this cam don't record (it worked right now becouse "-model" no equivalent "model" :)) But for comments after model names need add some code

Also possible add this logic:
1) if script see file wishlist.txt - use this file for record selected models ONLY (my current version)
2) if script see file ignorelist.txt - ignore this models (ignore form wishlist.txt also :))
3) if files both lists don't found - record all folowed models (your version)

This is universal solution. You can record all, record someone, don't record someone. But i think need create one modlist.txt and use advanced analysis: ignore models with sign "-" before name and record without. If ALL models have "-" - use this list like ignorelist :)

A bit messy. But it's just my ideas. Perhaps you might want to use something.

**Comment by marabu88** [comment]
**I update my version your script. Not very beautiful, but i think this is work
Check please**

**Comment by chopraaa** [comment]
@falsovsky I think tags are a good idea, and can be used for categorization. 

```
- completed
| - tag1
  | - model1
    | - video1
    | - video2
```
but ripping through a text file and checking everything would suck, and I prefer using something from the website itself. Using number of followers, location, age, etc, could be possible tags and could be scraped from the site itself.

@marabu88 Having a wishlist and an ignorelist serves no purpose. The models you're following are your wishlist, the others are getting ignored. Just follow the ones you actually want to record...

**Comment by falsovsky** [comment]
Hello, i'm not interested in your changes because they dont make any sense.

**Comment by marabu88** [comment]
I understand you. In any case, thanks for this script, as with slight modifications it works pretty well for me. I hope you are interested in how to catch bugs in the script (in the part that has not been rewritten by me). I have a suggestion that should interest you.
